config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  resources :books, only: [:new, :create]

end

app/models/book.rb
class Book < ActiveRecord::Base
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    
  end
  
  def create
    
    flash[:notice]="You created a book successfully"
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/new.html.erb
<%= form_for Book.new do |f| %>

 <label>Title:<%= f.text_field :title %></label>
 <label>Author:<%= f.text_field :author %></label>
 <%= f.submit "Create book" %>

<% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WellRead</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1><%= link_to "Sign up", new_user_registration_path %></h1>
<h1><%= link_to "Log in", new_user_session_path %></h1>
<h2><%= link_to "New book", new_book_path %></h2>